server {
    listen 80;
    server_name _;

    # Redirect all HTTP requests to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    # Cloudflare Origin Certificates (Must download from Cloudflare and place in /etc/nginx/ssl/)
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    # Allow large uploads for Media files (Music, Video)
    client_max_body_size 500M;

    # Proxy to Spring Boot API
    location / {
        proxy_pass http://micsu-app:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
